-- Sentencias para Insertar los Departamentos en la tabla de Departamento
INSERT INTO Departamento VALUES(91,'AMAZONAS'); 
INSERT INTO Departamento VALUES(05,'ANTIOQUIA' );
INSERT INTO Departamento VALUES(81,'ARAUCA' );
INSERT INTO Departamento VALUES(08,'ATLANTICO');
INSERT INTO Departamento VALUES(13,'BOLiVAR' );
INSERT INTO Departamento VALUES(15,'BOYACA' );
INSERT INTO Departamento VALUES(23,'CORDOBA');
INSERT INTO Departamento VALUES(17,'CALDAS' );
INSERT INTO Departamento VALUES(18,'CAQUETA' );
INSERT INTO Departamento VALUES(85,'CASANARE' );
INSERT INTO Departamento VALUES(19,'CAUCA' );
INSERT INTO Departamento VALUES(20,'CESAR' );
INSERT INTO Departamento VALUES(27,'CHOCO' );
INSERT INTO Departamento VALUES(25,'CUNDINAMARCA' );
INSERT INTO Departamento VALUES(94,'GUAINIA' );
INSERT INTO Departamento VALUES(44,'GUAJIRA' );
INSERT INTO Departamento VALUES(95,'GUAVIARE' );
INSERT INTO Departamento VALUES(41,'HUILA' );
INSERT INTO Departamento VALUES(47,'MAGDALENA');
INSERT INTO Departamento VALUES(50,'META' );
INSERT INTO Departamento VALUES(52,'NARIÑO' );
INSERT INTO Departamento VALUES(54,'NORTE DE SANTANDER' );
INSERT INTO Departamento VALUES(86,'PUTUMAYO' );
INSERT INTO Departamento VALUES(63,'QUINDIO' );
INSERT INTO Departamento VALUES(66,'RISARALDA' );
INSERT INTO Departamento VALUES(88,'SAN ANDRES' );
INSERT INTO Departamento VALUES(68,'SANTANDER' );
INSERT INTO Departamento VALUES(70,'SUCRE' );
INSERT INTO Departamento VALUES(73,'TOLIMA' );
INSERT INTO Departamento VALUES(76,'VALLE');
INSERT INTO Departamento VALUES(97,'VAUPES');
INSERT INTO Departamento VALUES(99,'VICHADA');


-- Sentencias para Insertar el tipo de Arma en la tabla de Arma_medio
INSERT INTO Arma_medio VALUES(01,'ARMA BLANCA / CORTOPUNZANTE');
INSERT INTO Arma_medio VALUES(02,'ARMA DE FUEGO');
INSERT INTO Arma_medio VALUES(03,'CONTUNDENTES');
INSERT INTO Arma_medio VALUES(04,'CORTANTES');
INSERT INTO Arma_medio VALUES(05,'CORTOPUNZANTES');
INSERT INTO Arma_medio VALUES(06,'NO REPORTADO');
INSERT INTO Arma_medio VALUES(07,'PUNZANTES');
INSERT INTO Arma_medio VALUES(08,'SIN EMPLEO DE ARMAS');
INSERT INTO Arma_medio VALUES(09,'NO REPORTA');
INSERT INTO Arma_medio VALUES(10,'ESCOPOLAMINA');


--Algunas Sentencias para Insertar los Municipios en la tabla de Municipio
INSERT INTO Municipio VALUES(08,8001,'BARRANQUILLA (CT)');
INSERT INTO Municipio VALUES(15,15238,'DUITAMA');
INSERT INTO Municipio VALUES(85,85139,'MANI');
INSERT INTO Municipio VALUES(25,25001,'BOGOTA D.C. (CT)');
INSERT INTO Municipio VALUES(70,70001,'SINCELEJO (CT)');
INSERT INTO Municipio VALUES(76,76001,'CALI (CT)');
INSERT INTO Municipio VALUES(41,41551,'PITALITO');
INSERT INTO Municipio VALUES(05,5308,'GIRARDOTA');
INSERT INTO Municipio VALUES(05,5360,'ITAGUI');
INSERT INTO Municipio VALUES(05,5380,'LA ESTRELLA');


--Algunas Sentencias para Insertar los Registros en la tabla de Registro_Delito
INSERT INTO Registro_Delito VALUES(01,08,8001,01,1/01/2010,'MASCULINO','ADULTOS',1);
INSERT INTO Registro_Delito VALUES(02,15,15238,01,1/01/2010,'FEMENINO','ADULTOS',1);
INSERT INTO Registro_Delito VALUES(03,18,18592,01,1/01/2010,'MASCULINO','ADULTOS',1);
INSERT INTO Registro_Delito VALUES(04,85,85139,01,1/01/2010,'FEMENINO','ADULTOS',1);
INSERT INTO Registro_Delito VALUES(05,25,25001,01,1/01/2010,'FEMENINO','ADULTOS',1);
INSERT INTO Registro_Delito VALUES(06,70,70001,01,1/01/2010,'FEMENINO','ADULTOS',1);
INSERT INTO Registro_Delito VALUES(07,76,76001,01,1/01/2010,'FEMENINO','ADULTOS',2);
INSERT INTO Registro_Delito VALUES(08,76,76001,01,1/01/2010,'MASCULINO','ADULTOS',2);
INSERT INTO Registro_Delito VALUES(09,76,76834,01,1/01/2010,'FEMENINO','ADULTOS',1);
INSERT INTO Registro_Delito VALUES(10,41,41551,02,1/01/2010,'FEMENINO','ADULTOS',1);
